[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "Rust Project Goals"

[preprocessor.goals]
command = "cargo run -p mdbook-goals --"

[preprocessor.goals.links]
"Help wanted" = "https://img.shields.io/badge/Help%20wanted-yellow"
"Complete" = "https://img.shields.io/badge/Complete-green"
"TBD" = "https://img.shields.io/badge/TBD-red"
"Team" = "https://img.shields.io/badge/Team%20ask-red"
"Not funded" = "https://img.shields.io/badge/Not%20yet%20funded-red"

[preprocessor.goals.linkifiers]
"RFC #([0-9]+)" = "https://github.com/rust-lang/rfcs/pull/$1"
"([a-zA-Z0-9-]+)/([a-zA-Z0-9-]+)#([0-9]+)" = "https://github.com/$1/$2/issues/$3"
"#([0-9]+)" = "https://github.com/rust-lang/rust/issues/$1"

[preprocessor.goals.users]
"@Nadrieril" = "@Nadrieril"
"@triagebot" = "@triagebot"

[output.html]
git-repository-url = "https://github.com/rust-lang/rust-project-goals"
edit-url-template = "https://github.com/rust-lang/rust-project-goals/edit/main/{path}"
site-url = "/rust-project-goals/"
additional-js = ["src/update-progress-bars.js"]

[output.html.fold]
enable = true
level = 0

[output.html.redirect]
"/2024h2/async_fn_everywhere.html" = "async.html"
"/2024h2/slate.html" = "index.html"
"/2024h2/orphaned.html" = "accepted.html"
"/2024h2/proposed.html" = "accepted.html"
"/2024h2/accepted.html" = "goals.html"
"/2024h2/flagship.html" = "goals.html"
"/introduction.html" = "index.html"
"/about/provisional_goals.html" = "about/invited_goals.html"

[output.markdown]
